services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - gemma2

  gemma2:
    hostname: ollama
    build:
      context: ./gemma2
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
